# Generated by Django 5.2.6 on 2025-09-19 03:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_fix_admin_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('periodo', models.CharField(max_length=7)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(default='expensa', max_length=30)),
                ('estado', models.CharField(default='PENDIENTE', max_length=15)),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('vivienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vivienda')),
            ],
            options={
                'db_table': 'factura',
                'unique_together': {('vivienda', 'periodo', 'tipo')},
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metodo', models.CharField(max_length=20)),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('comprobante_url', models.CharField(blank=True, max_length=200, null=True)),
                ('estado', models.CharField(default='PENDIENTE', max_length=20)),
                ('referencia_externa', models.CharField(blank=True, max_length=100, null=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='api.factura')),
            ],
            options={
                'db_table': 'pago',
            },
        ),
    ]
