# Generated by Django 5.2.6 on 2025-09-20 14:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_finanzas_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="pago",
            name="comentario",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="pago",
            name="registrado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pagos_registrados",
                to="api.usuario",
            ),
        ),
        migrations.CreateModel(
            name="FinanzasCodigoQR",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("imagen", models.FileField(upload_to="finanzas/qr/")),
                ("descripcion", models.CharField(blank=True, max_length=140)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="qr_actualizados",
                        to="api.usuario",
                    ),
                ),
            ],
            options={
                "db_table": "finanzas_codigo_qr",
            },
        ),
        migrations.CreateModel(
            name="NotificacionDirecta",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("titulo", models.CharField(max_length=120)),
                ("mensaje", models.TextField()),
                (
                    "estado",
                    models.CharField(
                        choices=[("ENVIADA", "Enviada"), ("LEIDA", "Leída")],
                        default="ENVIADA",
                        max_length=12,
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "enviado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notificaciones_enviadas",
                        to="api.usuario",
                    ),
                ),
                (
                    "factura",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notificaciones",
                        to="api.factura",
                    ),
                ),
                (
                    "pago",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notificaciones",
                        to="api.pago",
                    ),
                ),
                (
                    "residente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificaciones",
                        to="api.residente",
                    ),
                ),
            ],
            options={
                "db_table": "notificacion_directa",
                "ordering": ("-creado_en",),
            },
        ),
    ]
