# Generated by Django 5.2.6 on 2025-09-21 15:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_pago_comentario_pago_registrado_por_finanzascodigoqr_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aviso",
            name="fecha_creacion",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="aviso",
            name="estado",
            field=models.SmallIntegerField(
                choices=[(0, "Borrador"), (1, "Publicado")], default=0
            ),
        ),
        migrations.AlterField(
            model_name="aviso",
            name="fecha_publicacion",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
