# Generated by Django 5.2.6 on 2025-09-25 14:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_aviso_fecha_creacion_alter_aviso_estado_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaIncidenteSeguridad",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nombre", models.CharField(max_length=80, unique=True)),
                (
                    "descripcion",
                    models.CharField(blank=True, max_length=160, null=True),
                ),
                ("activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "seguridad_categoria_incidente",
                "ordering": ("nombre",),
            },
        ),
        migrations.CreateModel(
            name="RegistroAccesoVehicular",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("placa_detectada", models.CharField(max_length=20)),
                (
                    "confianza",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[("aprobado", "Aprobado"), ("rechazado", "Rechazado")],
                        max_length=12,
                    ),
                ),
                (
                    "imagen",
                    models.ImageField(
                        blank=True, null=True, upload_to="seguridad/accesos/"
                    ),
                ),
                ("respuesta_api", models.JSONField(blank=True, null=True)),
                ("comentario", models.TextField(blank=True, null=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "guardia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accesos_registrados",
                        to="api.usuario",
                    ),
                ),
                (
                    "vehiculo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accesos",
                        to="api.vehiculo",
                    ),
                ),
            ],
            options={
                "db_table": "seguridad_registro_acceso_vehicular",
                "ordering": ("-creado_en",),
            },
        ),
        migrations.CreateModel(
            name="ReporteIncidenteSeguridad",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("categoria_otro", models.CharField(blank=True, max_length=120)),
                ("descripcion", models.TextField(blank=True)),
                ("ubicacion", models.CharField(max_length=160)),
                ("es_emergencia", models.BooleanField(default=False)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("atendido", "Atendido"),
                            ("descartado", "Descartado"),
                        ],
                        default="pendiente",
                        max_length=12,
                    ),
                ),
                ("atendido_en", models.DateTimeField(blank=True, null=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incidentes",
                        to="api.categoriaincidenteseguridad",
                    ),
                ),
                (
                    "guardia_asignado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incidentes_atendidos",
                        to="api.usuario",
                    ),
                ),
                (
                    "residente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incidentes_reportados",
                        to="api.residente",
                    ),
                ),
            ],
            options={
                "db_table": "seguridad_reporte_incidente",
                "ordering": ("-creado_en",),
            },
        ),
    ]
