# Generated by Django 5.2.6 on 2025-09-25 14:40

from django.db import migrations


def seed_categories(apps, schema_editor):
    Category = apps.get_model("api", "CategoriaIncidenteSeguridad")
    defaults = [
        ("Actividad sospechosa", "Movimiento inusual o presencia de personas no identificadas."),
        ("Alarma de incendio", "Se detectó humo o fuego en instalaciones del condominio."),
        ("Mascota perdida", "Reporte de mascota sin supervisión o extraviada."),
        ("Vehículo desconocido", "Vehículo estacionado sin autorización dentro del condominio."),
    ]
    for nombre, descripcion in defaults:
        Category.objects.get_or_create(
            nombre=nombre,
            defaults={"descripcion": descripcion, "activo": True},
        )


def remove_categories(apps, schema_editor):
    Category = apps.get_model("api", "CategoriaIncidenteSeguridad")
    nombres = [
        "Actividad sospechosa",
        "Alarma de incendio",
        "Mascota perdida",
        "Vehículo desconocido",
    ]
    Category.objects.filter(nombre__in=nombres).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_categoriaincidenteseguridad_registroaccesovehicular_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_categories, remove_categories),
    ]
