"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.6.
"""

from pathlib import Path
import os
from datetime import timedelta
import dj_database_url  # 👈 importante para leer DATABASE_URL

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "SECRET_KEY", "django-insecure-$#@(2^+#9lw&fl0d&mnp=e=l+eds9heax_q4ic5rnjz1ismof^"
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "True") == "True"

ALLOWED_HOSTS = ["*"]

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "rest_framework",
    "rest_framework_simplejwt",
    'django_filters',
    "corsheaders",
    'api',
    'areas',
    'visitantes',
    'mantenimiento',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

# Database
# En local usará postgres con tus datos, en producción Railway usa DATABASE_URL
DATABASES = {
    "default":dj_database_url.parse(os.environ.get('DATABASE_URL', ''), conn_max_age=600) if os.environ.get('DATABASE_URL') else {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "condominio",
        "USER": "postgres",
        "PASSWORD": "calamaro123",
        "HOST": "127.0.0.1",
        "PORT": "5432",
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'America/La_Paz'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# Media files (uploads)
MEDIA_URL = os.environ.get("MEDIA_URL", "/media/")
MEDIA_ROOT = os.path.join(BASE_DIR, os.environ.get("MEDIA_ROOT", "media"))

# Asegura que las URL absolutas generadas desde el backend utilicen el esquema HTTPS
# cuando la aplicación está detrás de un proxy (por ejemplo, Railway + Vercel).
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django REST + JWT
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend"
    ],
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
}

# ⚡ CORS (para React en Vercel y desarrollo local)
CORS_ALLOW_ALL_ORIGINS = False


def _split_origins(value: str) -> list[str]:
    return [item.strip() for item in value.split(",") if item.strip()]


_base_cors_origins = [
    "https://condominio-peach.vercel.app",
    "https://condominio-production.up.railway.app",
]

_extra_cors_origins = os.environ.get("CORS_EXTRA_ORIGINS", "")
if _extra_cors_origins:
    _base_cors_origins.extend(_split_origins(_extra_cors_origins))

if DEBUG:
    _base_cors_origins.extend(
        [
            "http://localhost:3000",
            "http://127.0.0.1:3000",
            "http://localhost:5173",
            "http://127.0.0.1:5173",
        ]
    )


def _dedupe(items: list[str]) -> list[str]:
    # `dict.fromkeys` preserva el orden de inserción y elimina duplicados.
    return list(dict.fromkeys(items))


CORS_ALLOWED_ORIGINS = _dedupe(_base_cors_origins)


# CSRF
_base_csrf_trusted = [
    "https://condominio-peach.vercel.app",
    "https://condominio-production.up.railway.app",
]

_extra_csrf_trusted = os.environ.get("CSRF_EXTRA_TRUSTED_ORIGINS", "")
if _extra_csrf_trusted:
    _base_csrf_trusted.extend(_split_origins(_extra_csrf_trusted))

if DEBUG:
    _base_csrf_trusted.extend(
        [
            "http://localhost:3000",
            "http://127.0.0.1:3000",
            "http://localhost:5173",
            "http://127.0.0.1:5173",
        ]
    )

CSRF_TRUSTED_ORIGINS = _dedupe(_base_csrf_trusted)

# Email
EMAIL_BACKEND = os.environ.get("EMAIL_BACKEND")

EMAIL_HOST_USER = (
    os.environ.get("EMAIL_HOST_USER")
    or os.environ.get("GMAIL_USER", "")
)

_raw_password = (
    os.environ.get("EMAIL_HOST_PASSWORD")
    or os.environ.get("GMAIL_APP_PASSWORD")
    or ""
)
EMAIL_HOST_PASSWORD = _raw_password.replace(" ", "")

SENDGRID_API_KEY = os.environ.get("SENDGRID_API_KEY", "").strip()
if SENDGRID_API_KEY:
    # SendGrid usa "apikey" como usuario SMTP y la API key como contraseña.
    EMAIL_HOST_PASSWORD = SENDGRID_API_KEY
    if not EMAIL_HOST_USER:
        EMAIL_HOST_USER = os.environ.get("SENDGRID_USERNAME", "apikey")

EMAIL_HOST = os.environ.get("EMAIL_HOST", "")
if not EMAIL_HOST and EMAIL_HOST_USER.endswith("@gmail.com"):
    EMAIL_HOST = "smtp.gmail.com"
elif not EMAIL_HOST and SENDGRID_API_KEY:
    EMAIL_HOST = "smtp.sendgrid.net"

EMAIL_USE_SSL = os.environ.get("EMAIL_USE_SSL", "False") == "True"
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "True") == "True"

if EMAIL_USE_SSL:
    EMAIL_USE_TLS = False

default_port = 465 if EMAIL_USE_SSL else 587
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", default_port))

EMAIL_TIMEOUT = int(os.environ.get("EMAIL_TIMEOUT", 20))

DEFAULT_FROM_EMAIL = (
    os.environ.get("DEFAULT_FROM_EMAIL")
    or EMAIL_HOST_USER
    or "no-reply@condominio.local"
)

if not EMAIL_BACKEND:
    if EMAIL_HOST and (EMAIL_HOST_USER or EMAIL_HOST_PASSWORD):
        EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    else:
        EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

# Template opcional para link directo de reseteo
PASSWORD_RESET_URL_TEMPLATE = os.environ.get("PASSWORD_RESET_URL_TEMPLATE", "")
PASSWORD_RESET_TOKEN_MINUTES = int(os.environ.get("PASSWORD_RESET_TOKEN_MINUTES", 15))
PASSWORD_RESET_EMAIL_SUBJECT = os.environ.get(
    "PASSWORD_RESET_EMAIL_SUBJECT",
    "Instrucciones para restablecer tu contraseña",
)

# Seguridad - Integración con Plate Recognizer
PLATE_RECOGNIZER_TOKEN = os.environ.get("PLATE_RECOGNIZER_TOKEN", "").strip()
PLATE_RECOGNIZER_ENDPOINT = os.environ.get(
    "PLATE_RECOGNIZER_ENDPOINT",
    "https://api.platerecognizer.com/v1/plate-reader/",
).strip()




