# Generated by Django 5.2.6 on 2025-09-26 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0008_seed_security_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ci', models.CharField(max_length=20, unique=True)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('autorizado', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('autorizado', 'Autorizado'), ('denegado', 'Denegado'), ('ingresado', 'Ingresado'), ('salida', 'salida')], default='pendiente', max_length=20)),
                ('foto_ingreso', models.ImageField(blank=True, null=True, upload_to='visitantes/ingresos/')),
                ('foto_salida', models.ImageField(blank=True, null=True, upload_to='visitantes/salida/')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_ingreso', models.DateTimeField(blank=True, null=True)),
                ('fecha_salida', models.DateTimeField(blank=True, null=True)),
                ('residente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='api.usuario')),
            ],
        ),
    ]
