# Generated by Django 5.2.6 on 2025-09-27 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_seed_security_categories'),
        ('visitantes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitante',
            name='autorizado',
        ),
        migrations.RemoveField(
            model_name='visitante',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='visitante',
            name='fecha_ingreso',
        ),
        migrations.RemoveField(
            model_name='visitante',
            name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='visitante',
            name='fecha_salida',
        ),
        migrations.RemoveField(
            model_name='visitante',
            name='foto_ingreso',
        ),
        migrations.RemoveField(
            model_name='visitante',
            name='foto_salida',
        ),
        migrations.RemoveField(
            model_name='visitante',
            name='motivo',
        ),
        migrations.RemoveField(
            model_name='visitante',
            name='residente',
        ),
        migrations.AddField(
            model_name='visitante',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='visitantes/fotos/'),
        ),
        migrations.CreateModel(
            name='HistorialVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('autorizado', 'Autorizado'), ('denegado', 'Denegado'), ('ingresado', 'Ingresado'), ('salida', 'Salida')], default='pendiente', max_length=20)),
                ('autorizado', models.BooleanField(default=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_ingreso', models.DateTimeField(blank=True, null=True)),
                ('fecha_salida', models.DateTimeField(blank=True, null=True)),
                ('foto_ingreso', models.ImageField(blank=True, null=True, upload_to='visitantes/ingresos/')),
                ('foto_salida', models.ImageField(blank=True, null=True, upload_to='visitantes/salida/')),
                ('residente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='api.usuario')),
                ('visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiales', to='visitantes.visitante')),
            ],
        ),
    ]
