# Generated by Django 5.2.6 on 2025-09-28 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitantes', '0002_remove_visitante_autorizado_remove_visitante_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitante',
            name='placa',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='visitante',
            name='vehiculo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
