# Generated by Django 5.2.6 on 2025-09-28 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitantes', '0003_visitante_placa_visitante_vehiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitante',
            name='notas',
            field=models.TextField(blank=True, help_text='Notas adicionales sobre el visitante', null=True),
        ),
    ]
