# Generated by Django 5.2.6 on 2025-09-28 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitantes', '0004_visitante_notas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitante',
            name='notas',
        ),
        migrations.RemoveField(
            model_name='visitante',
            name='placa',
        ),
        migrations.RemoveField(
            model_name='visitante',
            name='vehiculo',
        ),
        migrations.AddField(
            model_name='historialvisita',
            name='notas',
            field=models.TextField(blank=True, help_text='Notas adicionales sobre el visitante', null=True),
        ),
        migrations.AddField(
            model_name='historialvisita',
            name='placa',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historialvisita',
            name='vehiculo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
