# Generated by Django 5.2.6 on 2025-09-28 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='mantenimientos/'),
        ),
    ]
